;;; grammarly-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from grammarly.el

(autoload 'grammarly-check-text "grammarly" "\
Send the TEXT to check.

(fn TEXT)")
(register-definition-prefixes "grammarly" '("grammarly-"))

;;; End of scraped data

(provide 'grammarly-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; grammarly-autoloads.el ends here
