;;; evil-terminal-cursor-changer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from evil-terminal-cursor-changer.el

(autoload 'evil-terminal-cursor-changer-activate "evil-terminal-cursor-changer" "\
Enable evil terminal cursor changer." t)
(defalias 'etcc-on 'evil-terminal-cursor-changer-activate)
(autoload 'evil-terminal-cursor-changer-deactivate "evil-terminal-cursor-changer" "\
Disable evil terminal cursor changer." t)
(defalias 'etcc-off 'evil-terminal-cursor-changer-deactivate)
(register-definition-prefixes "evil-terminal-cursor-changer" '("etcc-"))

;;; End of scraped data

(provide 'evil-terminal-cursor-changer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-terminal-cursor-changer-autoloads.el ends here
