;;; currency-convert-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from currency-convert.el

(let ((loads (get 'currency-convert 'custom-loads))) (if (member '"currency-convert" loads) nil (put 'currency-convert 'custom-loads (cons '"currency-convert" loads)) (put 'convenience 'custom-loads (cons 'currency-convert (get 'convenience 'custom-loads)))))
(defvar currency-convert-exchangeratesapi-key "" "\
API key for exchangeratesapi.io. Leave blank to not use it.")
(custom-autoload 'currency-convert-exchangeratesapi-key "currency-convert" t)
(autoload 'currency-convert "currency-convert" "\
Convert AMOUNT from FROM-CURRENCY to one or more other currencies.

Due to inaccuracies in exchange rate data and floating point
arithmetic, the conversion is only suitable for everyday
purposes. Do not use it for business or investment decisions.

When used as an interactive command, AMOUNT, FROM-CURRENCY and
TO-CURRENCIES are input into the minibuffer.  If blank input is
given for TO-CURRENCIES, the conversion is done to all known
currencies.  The conversion is displayed in the *Currency* buffer.
If that buffer already exists, its contents are replaced with the
new conversion.

When called from Lisp, AMOUNT is an integer or floating point
number.  FROM-CURRENCY is the uppercase three-letter currency as a
string.  TO-CURRENCIES is either a currency string or a list of
one or more currency strings.

The return value is a list of (CURRENCY . AMOUNT) pairs.

(fn AMOUNT FROM-CURRENCY TO-CURRENCIES)" t)
(register-definition-prefixes "currency-convert" '("currency-convert-"))

;;; End of scraped data

(provide 'currency-convert-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; currency-convert-autoloads.el ends here
